---
#- name: config > Template
#  template:
#    src:  "{{ elasticsearch_config_template }}"
#    dest: "{{ elasticsearch_config_file }}"
#  notify:
#    - elasticsearch restart
#
#
# - name: Configure Elasticsearch.
#  lineinfile: >
#    dest=/etc/elasticsearch/elasticsearch.yml
#    regexp="{{ item.regexp }}"
#    line="{{ item.line }}"
#    state=present
#  with_items:
#    - { regexp: '^script\.disable_dynamic', line: 'script.disable_dynamic: true' }
#    - { regexp: 'network\.host', line: 'network.host: localhost' }