---
#- name: install libselinux-python binary for Ansible to work
#  yum: name=libselinux-python state=present
#  when: ansible_distribution_major_version|int < 22

#- name: Fedora download RPM file
#  get_url: url="https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ fedora_elasticsearch_version }}.noarch.rpm"  dest=/tmp/es.rpm
#  changed_when: false
#
#- name: Fedora install from RPM
#  yum: name=/tmp/es.rpm  state=present
#  when: ansible_distribution_major_version|int < 22
#
#- name: Fedora install from RPM
#  shell: dnf install /tmp/es.rpm -y
#  when: ansible_distribution_major_version|int >= 22

- name: install dependencies
  shell: dnf install gpg -y
  changed_when: false
  when: ansible_distribution_major_version|int >= 22

- name: Add Elasticsearch GPG key for Fedora
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

# Oracle Linux / RHEL / CentOS
- name: Add Elasticsearch repository for Fedora
  template:
    src: RHEL.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  changed_when: false

- name: Install ES for Oracle Linux / RHEL / CentOS
  yum:
    name={{item}}
    state=present
  when: ansible_distribution_major_version|int < 22
  with_items:
    - elasticsearch

- name: Fedora install from RPM
  shell: dnf install elasticsearch -y
  changed_when: false
  when: ansible_distribution_major_version|int >= 22

