---
- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    id: {{ elasticsearch_key_id }}
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{elasticsearch_version}}/debian stable main"
    update_cache: yes
    state: present

- name: Update apt cache if repository just added.
  apt: update_cache=yes

- name: Install Elasticsearch.
  apt: pkg=elasticsearch state=present
