- name: Install ES
  portinstall:
    name=elasticsearch
    state=present
  changed_when: false
  when: freebsd_install_from_ports|bool

- name: Convert package to ng
  shell: pkg2ng
  when: not freebsd_install_from_ports|bool
  changed_when: false

- name: Install ES
  pkgng:
    name=elasticsearch
    state=present
  when: not freebsd_install_from_ports|bool
