---
- name: Add Elasticsearch GPG key for Oracle Linux / RHEL / CentOS.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

# Oracle Linux / RHEL / CentOS
- name: Add Elasticsearch repository for Oracle Linux / RHEL / CentOS
  template:
    src: RHEL.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install ES for Oracle Linux / RHEL / CentOS
  yum:
    name={{item}}
    state=present
  with_items:
    - elasticsearch

