---
- name: Java check
  command: "java -version"
  always_run: yes
  failed_when: false
  changed_when: false
  register: _java_check_output

- name: Java check fail
  fail:
    msg: Need java, you can use https://github.com/weldpua2008/ansible-java
  when: _java_check_output.stdout is not defined